<?php
    header("Access-Control-Allow-Origin: *");
    header("Expires: Mon, 26 Jul 1997 05:00:00 GMT");
    header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");
    header("Cache-Control: no-store, no-cache, must-revalidate");
    header("Cache-Control: post-check=0, pre-check=0", false);
    header("Pragma: no-cache");

    $table_arr = [
        [
            'id'         => 1,
            'username'   => 'user-0',
            'sex'        => '女',
            'city'       => '城市-0',
            'sign'       => '签名-0',
            'experience' => 255,
            'logins'     => 24,
            'wealth'     => 82830700,
            'classify'   => '作家',
            'score'      => 57,
            'status'     => true
        ],
        [
            'id'         => 2,
            'username'   => 'user-0',
            'sex'        => '女',
            'city'       => '城市-0',
            'sign'       => '签名-0',
            'experience' => 255,
            'logins'     => 24,
            'wealth'     => 82830700,
            'classify'   => '钢琴家',
            'score'      => 57,
            'status'     => false
        ],
        [
            'id'         => 3,
            'username'   => 'user-0',
            'sex'        => '女',
            'city'       => '城市-0',
            'sign'       => '签名-0',
            'experience' => 255,
            'logins'     => 24,
            'wealth'     => 82830700,
            'classify'   => '漫画家',
            'score'      => 57,
            'status'     => true
        ],
        [
            'id'         => 4,
            'username'   => 'user-0',
            'sex'        => '女',
            'city'       => '城市-0',
            'sign'       => '签名-0',
            'experience' => 255,
            'logins'     => 24,
            'wealth'     => 82830700,
            'classify'   => '游泳家',
            'score'      => 57,
            'status'     => false
        ],
        [
            'id'         => 5,
            'username'   => 'user-0',
            'sex'        => '女',
            'city'       => '城市-0',
            'sign'       => '签名-0',
            'experience' => 255,
            'logins'     => 24,
            'wealth'     => 82830700,
            'classify'   => '摄影家',
            'score'      => 57,
            'status'     => true
        ],
        [
            'id'         => 6,
            'username'   => 'user-0',
            'sex'        => '女',
            'city'       => '城市-0',
            'sign'       => '签名-0',
            'experience' => 255,
            'logins'     => 24,
            'wealth'     => 82830700,
            'classify'   => '作家',
            'score'      => 57,
            'status'     => true
        ],
        [
            'id'         => 7,
            'username'   => 'user-0',
            'sex'        => '女',
            'city'       => '城市-0',
            'sign'       => '签名-0',
            'experience' => 255,
            'logins'     => 24,
            'wealth'     => 82830700,
            'classify'   => '作家',
            'score'      => 57,
            'status'     => true
        ],
        [
            'id'         => 8,
            'username'   => 'user-0',
            'sex'        => '女',
            'city'       => '城市-0',
            'sign'       => '签名-0',
            'experience' => 255,
            'logins'     => 24,
            'wealth'     => 82830700,
            'classify'   => '作家',
            'score'      => 57,
            'status'     => true
        ],
        [
            'id'         => 9,
            'username'   => 'user-0',
            'sex'        => '女',
            'city'       => '城市-0',
            'sign'       => '签名-0',
            'experience' => 255,
            'logins'     => 24,
            'wealth'     => 82830700,
            'classify'   => '作家',
            'score'      => 57,
            'status'     => true
        ],
        [
            'id'         => 10,
            'username'   => 'user-0',
            'sex'        => '女',
            'city'       => '城市-0',
            'sign'       => '签名-0',
            'experience' => 255,
            'logins'     => 24,
            'wealth'     => 82830700,
            'classify'   => '作家',
            'score'      => 57,
            'status'     => true
        ],
        [
            'id'         => 11,
            'username'   => 'user-0',
            'sex'        => '女',
            'city'       => '城市-0',
            'sign'       => '签名-0',
            'experience' => 255,
            'logins'     => 24,
            'wealth'     => 82830700,
            'classify'   => '作家',
            'score'      => 57,
            'status'     => true
        ],
        [
            'id'         => 12,
            'username'   => 'user-0',
            'sex'        => '女',
            'city'       => '城市-0',
            'sign'       => '签名-0',
            'experience' => 255,
            'logins'     => 24,
            'wealth'     => 82830700,
            'classify'   => '作家',
            'score'      => 57,
            'status'     => true
        ],
        [
            'id'         => 13,
            'username'   => 'user-0',
            'sex'        => '女',
            'city'       => '城市-0',
            'sign'       => '签名-0',
            'experience' => 255,
            'logins'     => 24,
            'wealth'     => 82830700,
            'classify'   => '作家',
            'score'      => 57,
        ],
        [
            'id'         => 14,
            'username'   => 'user-0',
            'sex'        => '女',
            'city'       => '城市-0',
            'sign'       => '签名-0',
            'experience' => 255,
            'logins'     => 24,
            'wealth'     => 82830700,
            'classify'   => '作家',
            'score'      => 57,
        ],
        [
            'id'         => 15,
            'username'   => 'user-0',
            'sex'        => '女',
            'city'       => '城市-0',
            'sign'       => '签名-0',
            'experience' => 255,
            'logins'     => 24,
            'wealth'     => 82830700,
            'classify'   => '作家',
            'score'      => 57,
        ],
        [
            'id'         => 16,
            'username'   => 'user-0',
            'sex'        => '女',
            'city'       => '城市-0',
            'sign'       => '签名-0',
            'experience' => 255,
            'logins'     => 24,
            'wealth'     => 82830700,
            'classify'   => '作家',
            'score'      => 57,
        ],
        [
            'id'         => 17,
            'username'   => 'user-0',
            'sex'        => '女',
            'city'       => '城市-0',
            'sign'       => '签名-0',
            'experience' => 255,
            'logins'     => 24,
            'wealth'     => 82830700,
            'classify'   => '作家',
            'score'      => 57,
        ],
        [
            'id'         => 18,
            'username'   => 'user-0',
            'sex'        => '女',
            'city'       => '城市-0',
            'sign'       => '签名-0',
            'experience' => 255,
            'logins'     => 24,
            'wealth'     => 82830700,
            'classify'   => '作家',
            'score'      => 57,
        ],
        [
            'id'         => 19,
            'username'   => 'user-0',
            'sex'        => '女',
            'city'       => '城市-0',
            'sign'       => '签名-0',
            'experience' => 255,
            'logins'     => 24,
            'wealth'     => 82830700,
            'classify'   => '作家',
            'score'      => 57,
        ],
        [
            'id'         => 20,
            'username'   => 'user-0',
            'sex'        => '女',
            'city'       => '城市-0',
            'sign'       => '签名-0',
            'experience' => 255,
            'logins'     => 24,
            'wealth'     => 82830700,
            'classify'   => '作家',
            'score'      => 57,
        ],
        [
            'id'         => 21,
            'username'   => 'user-0',
            'sex'        => '女',
            'city'       => '城市-0',
            'sign'       => '签名-0',
            'experience' => 255,
            'logins'     => 24,
            'wealth'     => 82830700,
            'classify'   => '作家',
            'score'      => 57,
        ],
        [
            'id'         => 22,
            'username'   => 'user-0',
            'sex'        => '女',
            'city'       => '城市-0',
            'sign'       => '签名-0',
            'experience' => 255,
            'logins'     => 24,
            'wealth'     => 82830700,
            'classify'   => '作家',
            'score'      => 57,
        ],
    ];

    $page  = empty($_GET['page']) ? 1 : $_GET['page'] ;
    $limit = empty($_GET['limit']) ? 10 : $_GET['limit'];

    $offset = ($page-1) * $limit;

    $table_arrs = array_slice($table_arr, $offset, $limit);

    $new_arr = [
        'code'  => 0,
        'msg'   => 1,
        'count' => count($table_arr),
        'data'  => $table_arrs,
    ];

    echo json_encode($new_arr,true);
    exit();
?>